services:
  app:
    build:
      context: .
    env_file:
      - .env
    init: true
    volumes:
      - ./shared:/app/shared
    networks:
      - default
      - external
  cache:
    image: varnish:7.7.3
    volumes:
      - ./infra/default.vcl:/etc/varnish/default.vcl:ro
    tmpfs:
      - /var/lib/varnish:exec,mode=1777
    depends_on:
      - app
    networks:
      - default
      - external
  proxy:
    image: traefik:v3.6.1
    command:
      - --entrypoints.web.address=:8080
      - --providers.file.filename=/etc/traefik/routes.yaml
    networks:
      - default
      - external
networks:
  external:
    name: ${NETWORK_NAME}
    external: true
