name: haih-site-dev
services:
  app:
    build:
      target: development
    ports:
      - '127.0.0.1:${APP_PORT:-3001}:3000'
    volumes:
      - ./app:/app/app
      - ./server:/app/server
      - ./public:/app/public
      - ./vite.config.ts:/app/vite.config.ts
      - ./react-router.config.ts:/app/react-router.config.ts
  proxy:
    ports:
      - '127.0.0.1:${SITE_PORT:-8087}:8080'
    volumes:
      - ./infra/routes.dev.yaml:/etc/traefik/routes.yaml:ro
    depends_on: !override
      - app
