http:
  routers:
    site:
      rule: Host(`haih.localhost`) || Host(`localhost`)
      entryPoints: [web]
      service: site
  services:
    site:
      loadBalancer:
        servers:
          - url: http://app:3000
